version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: dating_postgres
    restart: always
    environment:
      POSTGRES_USER: ksusha
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dating_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dating_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  bot:
    build: 
      context: .
    container_name: dating_bot
    restart: always
    env_file:
      - ./bot_service/.env
    depends_on:
      - postgres
      - rabbitmq

  moderation:
    build: 
      context: .
    container_name: beta_moder_service
    restart: always
    command: python beta_moder_service.py
    env_file:
      - ./bot_service/.env
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data: