services:
  postgres:
    image: postgres:15-alpine
    container_name: dating_postgres
    restart: always
    environment:
      POSTGRES_USER: ksusha
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: dating_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dating_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: dating_redis
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: 
      context: .
    container_name: dating_bot
    restart: always
    environment:
      - PYTHONPATH=/app
    working_dir: /app/bot_service
    command: python main.py
    env_file:
      - ./bot_service/.env
    depends_on:
      - postgres
      - rabbitmq
      - redis

  moderation:
    build: 
      context: .
    container_name: moderation_service
    restart: always
    environment:
      - PYTHONPATH=/app:/app/bot_service
    working_dir: /app/moderation_service
    command: python main.py
    env_file:
    - ./bot_service/.env
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8000:8000"

  recommendation_service:
    build: .
    container_name: recommendation_service
    restart: always
    environment:
      - PYTHONPATH=/app:/app/bot_service
    working_dir: /app/recommendation_service
    command: python main.py
    env_file:
      - ./bot_service/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8001:8001"

volumes:
  postgres_data: